services:

  api:
    build: .
    container_name: magic_api
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=models/stacking_model.pkl
      - SCALER_PATH=models/scaler.pkl
      - SELECTED_FEATURES_PATH=models/selected_features.json
      - BASELINE_STATS_PATH=models/baseline_stats.json
    volumes:
      - ./models:/app/models
      - ./mlruns:/app/mlruns
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: magic_frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - api
    restart: unless-stopped
